[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.png" # css files too
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.jpg" # css files too
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.svg" # css files too
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[plugins]]
package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  buildDir = "__sapper__/export"
    exclude = [
    './__sapper__/export/service-worker-index.js',
    './__sapper__/export/service-worker.js',
    './__sapper__/export/service-worker-index',
    '**/**/service-worker-index',
  ]